name: deploy pages

on: [push]

jobs:
  deploy:
    runs-on: Ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true
      - name: Build webpage
        run: |
            cd public
            git checkout master
            cd -
            hugo --minify
      - name: publish
        env:
          USER_GITHUB_PAGES_TOKEN: ${{ secrets.USER_GITHUB_PAGES_TOKEN }}
        run: |
            git config --global user.name  "ToruNiina"
            git config --global user.email "niina.toru.68u@gmail.com"
            cd public
            git add .
            git commit -m "auto update"
            git push https://ToruNiina:${USER_GITHUB_PAGES_TOKEN}@github.com/ToruNiina/toruniina.github.io.git master
