name: deploy pages

on: [push]

jobs:
  deploy:
    runs-on: Ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true
      - name: Build webpage
        run: |
            hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.USER_GITHUB_PAGES_TOKEN }}
          external_repository: ToruNiina/toruniina.github.io
          publish_branch: master
          publish_dir: ./public
