name: deploy pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
      - name: Build webpage
        run: hugo
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name  "ToruNiina"
            git config --global user.email "niina.toru.68u@gmail.com"
            cd public
            git add .
            git commit -m "auto update"
            git push https://ToruNiina:${GITHUB_TOKEN}@github.com/ToruNiina/toruniina.github.io.git master
